# Rewrite requests to the Plone site using the VirtualHostMonster.

map $http_x_forwarded_proto $vhm_scheme {
    default $http_x_forwarded_proto;
    "" $scheme;
}

upstream plone {
    server plone:8080;
}

server {
    listen 9080;
    server_name _;

    location / {
        rewrite ^(.*)$ /VirtualHostBase/$vhm_scheme/$http_host/Plone/VirtualHostRoot$1 break;
        proxy_pass http://plone;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
